// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmSE8fRB7Kitkm4QHAlbhPIJfQXNjBP_0',
    appId: '1:398087171077:web:20321cfb2eb4da2673406c',
    messagingSenderId: '398087171077',
    projectId: 'sira-fbf75',
    authDomain: 'sira-fbf75.firebaseapp.com',
    storageBucket: 'sira-fbf75.firebasestorage.app',
    measurementId: 'G-L2G89LCHXT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLhCaneavSLOS-WT4HabJU1aedCvVMj14',
    appId: '1:398087171077:android:912f13eed81838ef73406c',
    messagingSenderId: '398087171077',
    projectId: 'sira-fbf75',
    storageBucket: 'sira-fbf75.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfYVzVxaVMPhVY23shS7R0kOB4Y3IRAmY',
    appId: '1:398087171077:ios:050d49a7f02edb8a73406c',
    messagingSenderId: '398087171077',
    projectId: 'sira-fbf75',
    storageBucket: 'sira-fbf75.firebasestorage.app',
    iosBundleId: 'com.loviaknh.sira',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfYVzVxaVMPhVY23shS7R0kOB4Y3IRAmY',
    appId: '1:398087171077:ios:050d49a7f02edb8a73406c',
    messagingSenderId: '398087171077',
    projectId: 'sira-fbf75',
    storageBucket: 'sira-fbf75.firebasestorage.app',
    iosBundleId: 'com.loviaknh.sira',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmSE8fRB7Kitkm4QHAlbhPIJfQXNjBP_0',
    appId: '1:398087171077:web:3890fedc63564caa73406c',
    messagingSenderId: '398087171077',
    projectId: 'sira-fbf75',
    authDomain: 'sira-fbf75.firebaseapp.com',
    storageBucket: 'sira-fbf75.firebasestorage.app',
    measurementId: 'G-HGZLZ0ZK7N',
  );
}
